name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full wget

      - name: 克隆仓库
        run: |
          git clone https://${{ secrets.PRIVATE_REPO_PAT }}@github.com/zyth3519/RimeConfig.git

      - name: 下载 Release 信息
        run: |
          cd RimeConfig
          mkdir -p tmp
          wget https://api.github.com/repos/amzxyz/rime_wanxiang/releases -O ./tmp/releases.json

      - name: 比较版本
        id: version
        run: |
          cd RimeConfig
          local_version=$(cat version.txt)
          remote_version=$(bash get_last_version.sh)
          res=$(bash compare_versions.sh "$local_version" "$remote_version")

          echo "local_version=$local_version"
          echo "remote_version=$remote_version"
          echo "compare_result=$res"

          if (( res == 2 )); then
            echo "UPDATE_CONFIG=true" >> $GITHUB_ENV
            echo "version=$remote_version" >> $GITHUB_OUTPUT
          fi

      - name: 下载配置文件
        if: env.UPDATE_CONFIG == 'true'
        run: |
          cd RimeConfig
          wget https://github.com/amzxyz/rime_wanxiang/releases/download/${{ steps.version.outputs.version }}/rime-wanxiang-base.zip -O ./tmp/rime-wanxiang-base.zip

      - name: 下载词库文件
        run: |
          cd RimeConfig
          wget https://github.com/amzxyz/rime_wanxiang/releases/download/dict-nightly/base-dicts.zip -O ./tmp/base-dicts.zip

      - name: 更新配置
        if: env.UPDATE_CONFIG == 'true'
        run: |
          cd RimeConfig
          rm -rf ./tmp/config
          mkdir -p ./tmp/config
          7z x ./tmp/rime-wanxiang-base.zip -o./tmp/config
          cp -rf ./tmp/config/* .

      - name: 更新词库
        run: |
          cd RimeConfig
          rm -rf ./tmp/base-dicts
          mkdir -p ./tmp/base-dicts
          7z x ./tmp/base-dicts.zip -o./tmp/base-dicts
          cp -rf ./tmp/base-dicts/* dicts

      - name: 判断是否需要更新
        id: check_changes
        run: |
          cd RimeConfig
          if git status --porcelain | grep .; then
            echo "NEED_PUSH=true" >> $GITHUB_ENV
          else
            echo "没有文件变化，不需要提交"
          fi

      - name: 生成提交信息
        if: env.NEED_PUSH == 'true'
        id: commitmsg
        run: |
          cd RimeConfig

          if [ "${UPDATE_CONFIG}" = "true" ]; then
            msg="更新配置到 ${{ steps.version.outputs.version }} 并同步词库"
          else
            msg="同步最新词库"
          fi

          echo "message=$msg" >> $GITHUB_OUTPUT
          echo "提交信息: $msg"

      - name: Push Main
        if: env.NEED_PUSH == 'true'
        run: |
          cd RimeConfig
          git config user.name "zyth3519"
          git config user.email "zythpang@github.com"
          git add .
          git commit -m "${{ steps.commitmsg.outputs.message }}"
          git push origin main

      - name: Push Android
        if: env.NEED_PUSH == 'true'
        run: |
          cd RimeConfig
          git fetch origin android
          git switch android || git switch -c android --track origin/android
          git merge main -m "合并 main"
          git push origin android